name: d_zoneeee
description: "Dead Zone Mapper App"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.19.0
  google_maps_flutter: ^2.12.1
  cupertino_icons: ^1.0.8
  firebase_core: ^2.30.0
  cloud_firestore: ^4.14.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  fl_chart: ^0.66.0
  intl: ^0.19.0
  lottie: ^2.3.1
  crypto: ^3.0.2
  timezone: ^0.9.3
  permission_handler: ^11.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/deadzone.json
    - assets/lottie/Animation - 1747340042836.json
